### ISSUE TITLE
external_renderer_ipc.dll有问题，但是找不到官方反馈渠道或者来源

### ISSUE THREAD

**Issue by Cassy-Lee** [MaaXYZ/EmulatorExtras#1]
根据API Monitor，nemu_connect会尝试读取`{第一个参数}\vms\MuMuPlayer-12.0-{第二个参数}\MuMuPlayer-12.0-{第二个参数}.nemu`，但是对于明日方舟特供版mumu应该是`{第一个参数}\vms\YXArkNights-12.0-{第二个参数}\YXArkNights-12.0-{第二个参数}.nemu`

**Comment by MistEO** [comment]
和 Mumu 的大佬们反馈了，得到的答复是已知问题，专版用不了这个 API，相关开发计划还在排期

**Comment by Cassy-Lee** [comment]
似乎找到了一个临时解决方法：
创建一个MuMuPlayer-12.0-0/MuMuPlayer-12.0-0.nemu到YXArkNights-12.0-0/YXArkNights-12.0-0.nemu的硬链接
在MAA里试过可以用
不知道为什么软链接似乎不能用，没有仔细测
直接复制应该不行，每次启动的时候似乎都会变化

**Comment by MistEO** [comment]
专版已经支持了

另外国际版 mumu 还是不支持，得到的答复是已经不维护了
